openapi: '3.0.2'
info:
  title: 'Country-Currencies'
  version: '1.0.0'
servers:
  - url: http://localhost:8081/v1
paths:
  /countries/europe:
    get:
      parameters:
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/orderBy'
      responses:
        '200':
          $ref: '#/components/responses/countriesResponse'
  /currencies/world:
    get:
      responses:
        '200':
          $ref: '#/components/responses/currenciesResponse'
components:
  responses:
    countriesResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/countries'
    currenciesResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/currencies'
  parameters:
    sortBy:
      name: sortBy
      in: query
      schema:
        $ref: '#/components/schemas/sortBy'
    orderBy:
      name: orderBy
      in: query
      schema:
        $ref: '#/components/schemas/orderBy'
  schemas:
    sortBy:
      type: string
      enum:
        - country
        - currency
      default: country
    orderBy:
      type: string
      enum:
        - ascending
        - descending
      default: ascending
    countries:
      type: object
      description: Keys are country names. Values are the respective countries' currency
      additionalProperties:
        type: string
      example:
        Liechtenstein: CHF
        Norway: NOK
        Switzerland: CHF
    currencies:
      type: object
      description: Keys are currencies. Values are lists of country names wherein the currency is used
      additionalProperties:
        type: array
        description:
          List of countries using the same currency
        items:
          type: string
          description: Country name
      example:
        CHF:
          - Liechtenstein
          - Switzerland
        NOK:
          - Norway
